db:
  adapter: postgresql
  host: localhost
  user: postgres
pagination:
  page_size: 10
rabbitmq:
  consumer_pool: 10
secret_code: super_secret_code
app:
  name: auth
logger:
  path: log/app.log
  level: info
